CREATE TABLE CSETEAM61.CIRCLEMEMBER(
CIRCLEID VARCHAR(20),
USERID VARCHAR(20),
FOREIGN KEY (CIRCLEID) REFERENCES CSETEAM61.CIRCLES(CIRCLEID),
FOREIGN KEY (USERID) REFERENCES CSETEAM61.USERS(USERID)
);