CREATE TABLE CSETEAM61.CIRCLES(
CIRCLEID VARCHAR(20) NOT NULL,
CIRCLENAME VARCHAR(20) NOT NULL,
OWNER VARCHAR(20),
PRIMARY KEY(CIRCLEID),
FOREIGN KEY(OWNER) REFERENCES CSETEAM61.USERS(USERID) ON DELETE SET NULL ON UPDATE NO ACTION 
);