CREATE TABLE CSETEAM61.MSGRECEIVER(
MESSAGEID VARCHAR(10),
RECEIVER VARCHAR(20),
FOREIGN KEY(RECEIVER)REFERENCES CSETEAM61.USERS(USERID) ON DELETE SET NULL ON UPDATE NO ACTION,
FOREIGN KEY(MESSAGEID)REFERENCES CSETEAM61.MESSAGES(MESSAGEID) ON DELETE SET NULL ON UPDATE NO ACTION
);