CREATE TABLE CSETEAM61.SALES(
TRANSACTIONID VARCHAR(10) NOT NULL,
ADVTID VARCHAR(20)NOT NULL,
DATENTIME DATE,
NOOFUNITSOLD INTEGER,
USERID VARCHAR(20)NOT NULL,
PRIMARY KEY (TRANSACTIONID),
UNIQUE(TRANSACTIONID, USERID),
FOREIGN KEY(USERID)REFERENCES CSETEAM61.USERS(USERID),
FOREIGN KEY(ADVTID)REFERENCES CSETEAM61.ADVERTISEMENTS(ADVTID)
);