CREATE TABLE CSETEAM61.SIPOSTS(
SIPOSTID VARCHAR(10) UNIQUE NOT NULL,
DATENTIME DATE,
CONTENT VARCHAR(255),
POSTAUTHOR VARCHAR(20),
PAGEID VARCHAR(20),
PRIMARY KEY(SIPOSTID),
FOREIGN KEY(POSTAUTHOR)REFERENCES CSETEAM61.USERS(USERID) ON DELETE SET NULL ON UPDATE NO ACTION,
FOREIGN KEY(PAGEID)REFERENCES CSETEAM61.SIPTOPAGE(PAGEID) ON DELETE SET NULL ON UPDATE NO ACTION

);