CREATE TABLE CSETEAM61.USERS(
USERID VARCHAR(20) NOT NULL,
FIRSTNAME VARCHAR(20)NOT NULL,
LASTNAME VARCHAR(20)NOT NULL,
SEX VARCHAR(6),
EMAILID VARCHAR(20)NOT NULL,
DOB DATE NOT NULL,
ADDRESS VARCHAR(256),
ZIPCODE INTEGER,
FOREIGN KEY(ZIPCODE) REFERENCES CSETEAM61.ZIPLOCATION(ZIPCODE)ON DELETE SET NULL ON UPDATE NO ACTION, 
PRIMARY KEY(USERID),
UNIQUE (FIRSTNAME,EMAILID)
);