CREATE TABLE CSETEAM61.WALL(
POSTID VARCHAR(10) NOT NULL,
WALLOWNER VARCHAR(20) NOT NULL,
DATENTIME DATE,
CONTENT VARCHAR(255),
UNIQUE (POSTID, WALLOWNER),
FOREIGN KEY(WALLOWNER)REFERENCES CSETEAM61.USERS(USERID)
);